name: CI
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t rishemgulov/skypro_rishemgulov:$GITHUB_REF_NAME-$GITHUB_RUN_ID ./sky-lessons/CurseJob3/
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker tag
        run: docker tag skypro_rishemgulov:$GITHUB_REF_NAME-$GITHUB_RUN_ID:first_tag rishemgulov/skypro_rishemgulov:$GITHUB_REF_NAME-$GITHUB_RUN_ID:first_tag
      - name: docker push
        run: docker push rishemgulov/skypro_rishemgulov:$GITHUB_REF_NAME-$GITHUB_RUN_ID:first_tag
